x-app: &default-app
  platform: linux/amd64
  networks:
    - app-network

services:
  app:
    <<: *default-app
    build:
      context: .
      target: app_runner
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
  test:
    <<: *default-app
    build:
      context: .
      target: app_tester
    command: ./gradlew test

networks:
  app-network:
    driver: bridge