server:
  port: ${SERVER_PORT:6001}

springdoc:
  swagger-ui:
    path: /docs
  packages-to-scan: com.mycompany.shopping
  paths-to-match: /**

spring:
  application:
    name: shopping-api
  r2dbc:
    url: r2dbc:h2:mem:///testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      port: 8090
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
